# coding=utf-8
from django.core.management.base import CommandError, NoArgsCommand
from django.utils import timezone

from v2ex.babel.models import Section,Node
import random

class Command(NoArgsCommand):
    help = "Ensures templates stored in the database don't have syntax errors."

    def handle_noargs(self, **options):
        errors = []

        sections_names = [
        (1,'Limbo', u'混沌海'),
        (2,'Mechanus', u'机械境'),
        (3,'GrayWaste', u'灰色荒野'),
        (4,'Elysium', u'极乐境'),
        (5,'Sigil', u'法印城'),
        ]
        
        nodes=[
        (1,[('earth', u'地球'),
('qna', u'问与答'),
('shanghai', u'上海'),
('beijing', u'北京'),
('guangzhou', u'广州'),
('shenzhen', u'深圳'),
('lijiang', u'丽江'),
('hangzhou', u'杭州'),
('guilin', u'桂林'),
('chengdu', u'成都'),
('chongqing', u'重庆'),
('tokyo', u'东京'),
('kunming', u'昆明'),
('guiyang', u'贵阳'),
('jobs', u'酷工作'),
('tianjin', u'天津'),
('nyc', u'New York'),
('all4all', u'二手交易'),
('wuhan', u'武汉'),
('hongkong', u'香港'),
('macau', u'澳门'),
('bayarea', u'湾区'),
('berlin', u'Berlin'),
('taipei', u'台北'),
('tengzhou', u'滕州'),
('xiamen', u'厦门'),
('hohhot', u'呼和浩特'),
('nanjing', u'南京'),
('xian', u'西安'),
('daqing', u'大庆'),
('sanya', u'三亚'),
('haikou', u'海口'),
('zhuhai', u'珠海'),
('dalian', u'大连'),
('gyyz', u'贵阳一中'),
('ynsdfz', u'云南师大附中'),
('london', u'London'),
('wuxi', u'无锡'),
('zhengzhou', u'郑州'),
('fuzhou', u'福州'),
('jinan', u'济南'),
('lanzhou', u'兰州'),
('qingdao', u'青岛'),
('suzhou', u'苏州'),
('yangzhou', u'扬州'),
('kyoto', u'京都'),
('siliconvalley', u'硅谷'),
('seattle', u'Seattle'),
('sydney', u'Sydney'),
('changsha', u'长沙'),
('paris', u'Paris'),
('dubai', u'Dubai'),
('singapore', u'Singapore'),
('whu', u'武汉大学'),
('pku', u'北京大学'),
('tsinghua', u'清华大学'),
('sjtu', u'上海交通大学'),
('sysu', u'中山大学'),
('oslo', u'Oslo'),
('stockholm', u'Stockholm'),
('portland', u'Portland'),
('jp', u'日本'),
('findpeople', u'寻人'),
('xinyu', u'新余'),
('yueyang', u'岳阳'),
('dali', u'大理'),
('changchun', u'长春'),
('zunyi', u'遵义'),
('xining', u'西宁'),
('harbin', u'哈尔滨'),
('nanchang', u'南昌'),
('baoding', u'保定'),
('tongren', u'铜仁'),
('chicago', u'Chicago'),
('jlu', u'吉林大学'),
('ustc', u'中国科学技术大学'),
('la', u'Los Angeles'),
('visa', u'签证'),
('europe', u'欧洲'),
('uk', u'英国'),
('us', u'美国'),
('se', u'瑞典'),
('de', u'德国'),
('ningbo', u'宁波'),
('sv', u'硅谷'),
('xindanwei', u'新单位'),
('pasadena', u'Pasadena'),
('santamonica', u'Santa Monica'),
('sanfrancisco', u'San Francisco'),
('lasvegas', u'Las Vegas'),
('california', u'California'),
('ca', u'加拿大'),
('cn', u'中国'),
('mx', u'墨西哥'),
('kr', u'韩国'),
('asia', u'亚洲'),
('tw', u'台湾'),]),

        (2,[
('babel', u'Project Babel'),
('bfbc2', u'BFBC2'),
('iphone', u'iPhone'),
('ipad', u'iPad'),
('mbp', u'MacBook Pro'),
('linux', u'Linux'),
('idev', u'iDev'),
('gae', u'Google App Engine'),
('macosx', u'Mac OS X'),
('picky', u'Project Picky'),
('nds', u'NDS'),
('ps3', u'PlayStation 3'),
('xbox360', u'Xbox 360'),
('psp', u'PSP'),
('wii', u'Wii'),
('kindle', u'Kindle'),
('android', u'Android'),
('imac', u'iMac'),
('re5', u'Resident Evil 5'),
('icode', u'iCode'),
('redis', u'Redis'),
('steam', u'Steam'),
('nosql', u'NoSQL'),
('hardware', u'硬件'),
('adobe', u'Adobe'),
('games', u'游戏'),
('internet', u'互联网'),
('c', u'C/C++/Obj-C'),
('photoshop', u'Photoshop'),
('html', u'HTML'),
('mysql', u'MySQL'),
('php', u'PHP'),
('java', u'Java'),
('3g', u'3G'),
('iad', u'iAd'),
('ilife', u'iLife'),
('iwork', u'iWork'),
('vpn', u'VPN'),
('macpro', u'Mac Pro'),
('server', u'服务器'),
('ror', u'Ruby on Rails'),
('nginx', u'Nginx'),
('macmini', u'Mac mini'),
('macbook', u'MacBook'),
('moh', u'Medal of Honor'),
('wordpress', u'WordPress'),
('python', u'Python'),
('firefox', u'Firefox'),
('chrome', u'Chrome'),
('safari', u'Safari'),
('opera', u'Opera'),
('sc2', u'StarCraft 2'),
('openstack', u'OpenStack'),
('git', u'git'),
('blogger', u'Blogger'),
('cloud', u'云计算'),
('bzr', u'bzr'),
('bb', u'宽带症候群'),
('search', u'搜索引擎技术研究'),
('oauth', u'OAuth'),
('perl', u'Perl'),
('scala', u'Scala'),
('io', u'io'),
('apache', u'Apache'),
('couchdb', u'CouchDB'),
('imarketing', u'iMarketing'),
('arcade', u'街机游戏'),
('http', u'HTTP'),
('toruk', u'Toruk'),
('re', u'正则表达式'),
('css', u'CSS'),
('dell', u'Dell'),
('js', u'JavaScript'),
('lua', u'Lua'),
('blackberry', u'BlackBerry'),
('pixel', u'像素'),
('hadoop', u'Hadoop'),
('mapreduce', u'MapReduce'),
('cocos2d', u'cocos2d'),
('ipod', u'iPod'),
('appletv', u'Apple TV'),
('matrix', u'Matrix'),
('igame', u'iGame'),
('accessory', u'配件'),
('erlang', u'Erlang'),
('car', u'汽车'),
('copter', u'直升机'),
('opensolaris', u'OpenSolaris'),
('moinmoin', u'MoinMoin'),
('apple', u'Apple'),
('bluray', u'Blu-ray'),
('assembly', u'汇编'),
('ssh', u'SSH'),
('camino', u'Camino'),
('mobileme', u'MobileMe'),
('flash', u'Flash'),
('dns', u'DNS'),
('cray', u'Cray'),
('xen', u'Xen'),
('riak', u'Riak'),
('podcast', u'Podcast'),
('autocad', u'AutoCAD'),
('diablo3', u'Diablo III'),
('nokia', u'Nokia'),
('mozilla', u'Mozilla'),
('cod', u'Call of Duty'),
('stop', u'STOP'),
('vim', u'vim'),
('emacs', u'Emacs'),
('fcp', u'Final Cut Pro'),
('motion', u'Motion'),
('security', u'网络安全'),
('entropy', u'熵'),
('webos', u'webOS'),
('lisp', u'Lisp'),
('energy', u'能源'),
('nfs', u'Need for Speed'),
('textie', u'Textie'),
('dropbox', u'Dropbox'),
('bicycle', u'自行车'),
('alienware', u'Alienware'),
('sqlite', u'SQLite'),
('sony', u'SONY'),
('gamedevstory', u'Game Dev Story'),
('aws', u'Amazon Web Services'),
('programmer', u'程序员'),
('designer', u'设计师'),
('transformers', u'变形金刚'),
('api', u'API'),
('mongodb', u'MongoDB'),
('fanfou', u'饭否 API'),
('lbp', u'小小大星球'),
('3ds', u'3DS'),
('bf3', u'Battlefield 3'),
('curl', u'cURL'),
('mba', u'MacBook Air'),
('asana', u'Asana'),
('asdf', u'asdf'),
('adsense', u'AdSense'),
('adwords', u'AdWords'),
('cuttherope', u'Cut the Rope'),
('killzone', u'Killzone'),
('webmaster', u'站长'),
('blackmagic', u'黑魔法'),
('minecraft', u'Minecraft'),
('leica', u'莱卡'),
('canon', u'佳能'),
('nikon', u'尼康'),
('bento', u'Bento'),
('instapaper', u'Instapaper'),
('dribbble', u'Dribbble'),
('dotnet', u'.NET'),
('ontology', u'本体论'),
('alexa', u'Alexa'),
('3dsmax', u'3ds Max'),
('admob', u'AdMob'),
('windows', u'Windows'),
('tornado', u'Tornado'),
('gw2', u'Guild Wars 2'),
('postgresql', u'PostgreSQL'),
('guide', u'使用指南'),
('ruby', u'Ruby'),
('portal', u'Portal series'),
('logitech', u'罗技'),
('fusionio', u'Fusion-io'),
('irobot', u'iRobot'),
('go', u'Go'),
('pal', u'仙剑奇侠传'),
('wow', u'World of Warcraft'),
('crysis', u'Crysis'),
('wp', u'Windows Phone'),
('arch', u'Arch'),
('gtd', u'Getting Things Done'),
('opensource', u'开源软件'),
('gcc', u'GCC'),
('llvm', u'LLVM'),
('amd', u'AMD'),
('intel', u'Intel'),
('nvidia', u'NVIDIA'),
('maya', u'Maya'),
('shade', u'Shade'),
('bitcoin', u'Bitcoin'),
('stormwind', u'Project Stormwind'),
('reddit', u'reddit'),
('oracle', u'Oracle'),
('bing', u'Bing'),
('pixelmator', u'Pixelmator'),
('jekyll', u'Jekyll'),
('yc', u'Y Combinator'),
('arc', u'Arc'),
('programming', u'编程'),
('os', u'操作系统'),
('vcs', u'版本控制系统'),
('frameworks', u'编程框架'),
('software', u'软件'),
('computers', u'计算机'),
('consoles', u'游戏主机'),
('basic', u'BASIC'),
('db', u'数据库'),
('browsers', u'浏览器'),
('mercurial', u'Mercurial'),
('cobra', u'Cobra'),
('jquery', u'jQuery'),
('wwdc', u'WWDC'),
('psvita', u'PlayStation Vita'),
('ea', u'EA'),
('nintendo', u'Nintendo'),
('icloud', u'iCloud'),
('django', u'Django'),
('celery', u'Celery'),
('instagram', u'Instagram'),
('nodejs', u'node.js'),
('dotcloud', u'DotCloud'),
('wave', u'Google Wave Protocol'),
('ifttt', u'ifttt'),
('lumix', u'LUMIX'),
('gopro', u'GoPro'),
('itunes', u'iTunes'),
('appstore', u'App Store'),
('tech', u'科技'),
('rage', u'RAGE'),
('opengl', u'OpenGL'),
('directx', u'DirectX'),
('dust514', u'DUST 514'),
('gnome', u'Gnome'),
('dota', u'DotA'),
('cdn', u'CDN'),
('lol', u'英雄联盟'),
('scrum', u'Scrum'),
('centos', u'CentOS'),
('gamedev', u'游戏开发'),
('udk', u'Unreal Development Kit'),
('vmware', u'VMware'),
('glassfish', u'GlassFish'),
('jinja', u'Jinja'),
('unity', u'UNITY'),
('blender', u'Blender'),
('3d', u'3D'),
('zeppelin', u'Project Zeppelin'),
('flask', u'Flask'),
('razer', u'Razer'),
('netbeans', u'NetBeans'),
('clojure', u'Clojure'),
('coldfusion', u'ColdFusion'),
('whatsapp', u'WhatsApp'),
('backbone', u'Backbone.js'),
('textmate', u'TextMate'),
('editors', u'编辑器'),
('sae', u'Sina App Engine'),
('svn', u'Subversion'),
('lego', u'LEGO'),
('asteroid', u'Project Asteroid'),
('inc', u'公司运营'),
('alipay', u'支付宝'),
('xcode', u'Xcode'),
('skyrim', u'上古卷轴 V'),
('mgs', u'Metal Gear Solid'),
('homebrew', u'Homebrew'),
('rabbitmq', u'RabbitMQ'),
('gta', u'Grand Theft Auto'),
('indesign', u'InDesign'),
('illustrator', u'Illustrator'),
('fling', u'Fling'),
('pogo', u'Pogo'),
('freebsd', u'FreeBSD'),
('trello', u'Trello'),
('lighttpd', u'Lighttpd'),
('arduino', u'Arduino'),
('cv', u'求职'),
('gt', u'Gran Turismo'),
('charles', u'Charles'),
('eve', u'EVE'),
('wacom', u'Wacom'),
('markdown', u'Markdown'),
('zope', u'Zope'),
('ibook', u'iBook'),
('galaxy', u'Project Galaxy'),
('museum', u'Project Museum'),
('0x10c', u'0x10c'),
('dn', u'域名'),
('meteor', u'Meteor'),
('haskell', u'Haskell'),
('sqlalchemy', u'SQLAlchemy'),
('storm', u'Storm'),
('sublime', u'Sublime Text'),
('ubuntu', u'Ubuntu'),
('fedora', u'Fedora'),
('gentoo', u'Gentoo'),
('evernote', u'Evernote'),
('sandbox', u'沙盒'),
('reprocess', u'信息处理中心'),
('time', u'时间'),
('dev', u'Dev'),
('lightroom', u'Lightroom'),
('aperture', u'Aperture'),
('stripe', u'Stripe'),
('gwan', u'G-WAN'),
('squid', u'Squid'),
('velocity', u'Velocity'),
('openbsd', u'OpenBSD'),
('haproxy', u'HAProxy'),
('mece', u'MECE'),
('c3edge', u'C3Edge'),
('snort', u'Snort'),
('ssl', u'SSL'),
('rrdtool', u'RRDtool'),
('xenserver', u'XenServer'),
('puppet', u'Puppet'),
('doitim', u'Doit.im'),
('cloudstack', u'CloudStack'),
('simcity', u'SimCity'),
('varnish', u'Varnish'),
('rq', u'RQ'),
('kde', u'KDE'),
('hawken', u'Hawken'),
('ios', u'iOS'),
('azure', u'Windows Azure'),
('iis', u'IIS'),
('newrelic', u'New Relic'),
('make', u'make'),
('oreilly', u"O'Reilly"),
('delphi', u'Delphi'),
('4g', u'4G'),
('memsql', u'MemSQL'),
('openvz', u'OpenVZ'),
('edgecast', u'EdgeCast'),
('fitbit', u'Fitbit'),
('couchbase', u'Couchbase'),
('cassandra', u'Cassandra'),
('hbase', u'HBase'),
('lucene', u'Lucene'),
('erp', u'ERP'),
('cisco', u'Cisco'),
('solr', u'Solr'),
('openshift', u'OpenShift'),
('orca', u'ORCA'),
('meizu', u'魅族'),
('computervision', u'Computer vision'),
('stackoverflow', u'Stack Overflow'),
('nexus', u'Nexus'),
('appnet', u'App.net'),
('elasticsearch', u'elasticsearch'),
('passenger', u'Phusion Passenger'),
('anno', u'Anno'),
('chocolat', u'Chocolat'),
('bigdata', u'Big Data'),
('devops', u'DevOps'),
('virtualbox', u'VirtualBox'),
('cherokee', u'Cherokee'),
('ubersmith', u'Ubersmith'),
('chef', u'Chef'),
('wesnoth', u'Battle for Wesnoth'),
('irc', u'IRC'),
('munin', u'Munin'),
('solaris', u'Solaris'),
('heroku', u'Heroku'),
('ingress', u'Ingress'),
('netbsd', u'NetBSD'),
('opennebula', u'OpenNebula'),
('juniper', u'Juniper'),
('ceph', u'Ceph'),
('swift', u'Swift'),
('splunk', u'Splunk'),
('stunnel', u'stunnel'),
('smartos', u'SmartOS'),
('zfs', u'ZFS'),
('atlassian', u'Atlassian'),
('sdn', u'SDN'),
('unix', u'Unix'),
('coc', u'Clash of Clans'),
('shadowsocks', u'shadowsocks'),
('pi', u'Raspberry Pi'),
('square', u'Square'),
('opensuse', u'openSUSE'),
('vps', u'VPS'),
('lxc', u'LXC'),
('confluence', u'Confluence'),
('wiki', u'Wiki'),
('plone', u'Plone'),
('sphinx', u'Sphinx'),
('rst', u'reStructuredText'),
('hubot', u'HUBOT'),
('vagrant', u'Vagrant'),
('ansible', u'Ansible'),
('ts', u'Traffic Server'),
('discourse', u'Discourse'),
('fluentd', u'Fluentd'),
('debian', u'Debian'),
('alfred', u'Alfred'),
('re6', u'Resident Evil 6'),
('cloudera', u'Cloudera'),
('ps4', u'PlayStation 4'),
('euca', u'Eucalyptus'),
('ml', u'机器学习'),
('paypal', u'PayPal'),
('openresty', u'OpenResty'),
('stash', u'Stash'),
('xehost', u'XeHost'),
('host700', u'HOST700'),
('elinkvps', u'ELINKVPS'),
('bf4', u'Battlefield 4'),
('smartisanos', u'Smartisan OS'),
('ssd', u'SSD'),
('aerofs', u'AeroFS'),
('miui', u'MIUI'),
('feo', u'前端优化'),
('sailfish', u'Sailfish'),
('mechanical', u'机械键盘'),
('line', u'LINE'),
('spark', u'Spark'),
('glass', u'Google Glass'),
('hardcore', u'发烧友'),
('emc', u'EMC'),
('microsoft', u'微软'),
('webrtc', u'WebRTC'),
('braun', u'Braun'),
('4k', u'4K'),
('duolingo', u'Duolingo'),
('core', u'Core'),
('lvm', u'LVM'),
('jira', u'JIRA'),
('bash', u'Bash'),
('oculusvr', u'Oculus VR'),
('btsync', u'BTSync'),
('itransfer', u'iTransfer'),
('mapr', u'MapR'),
('docker', u'Docker'),
('hyperloop', u'Hyperloop'),
('bootstrap', u'Bootstrap'),
('zookeeper', u'ZooKeeper'),
('ie', u'IE'),
('pdns', u'PowerDNS'),
('dyn', u'Dyn'),
('salt', u'Salt Stack'),
('sap', u'SAP'),]),

        (3,[('v2ex', u'V2EX'),
('olivida', u'OLIVIDA'),
('twitter', u'Twitter'),
('share', u'分享发现'),
('create', u'分享创造'),
('kk', u'Kevin Kelly'),
('autistic', u'自言自语'),
('youtube', u'YouTube'),
('google', u'Google'),
('vimeo', u'Vimeo'),
('4sq', u'foursquare'),
('feedback', u'反馈'),
('in', u'分享邀请码'),
('fml', u'糗事分享'),
('wikipedia', u'Wikipedia'),
('digg', u'Digg'),
('jiong', u'囧'),
('show', u'晒晒更健康'),
('livid', u'Livid'),
('pointless', u'无要点'),
('treehole', u'树洞'),
('eggpain', u'强迫症'),
('80days', u'80 天环游地球'),
('invest', u'投资'),
('dream', u'梦'),
('inception', u'Inception'),
('outsourcing', u'外包'),
('linode', u'Linode'),
('design', u'设计'),
('ideology', u'Ideology'),
('tc', u'TechCrunch'),
('quora', u'Quora'),
('rework', u'REWORK'),
('inbox', u'Inbox'),
('fengshui', u'风水'),
('iconfactory', u'Iconfactory'),
('hishim', u'他他'),
('herher', u'她她'),
('aden', u'亚丁湾'),
('lotr', u'指环王'),
('2012', u'2012'),
('facebook', u'Facebook'),
('tuan', u'团购分享'),
('diary', u'日记'),
('love', u'非诚勿扰'),
('angel', u'天使投资'),
('business', u'商业模式'),
('newbie', u'新手求助'),
('ted', u'TED'),
('flamewar', u'水深火热'),
('standard', u'标准'),
('scifi', u'科幻'),
('wtf', u'不靠谱茶话会'),
('528491', u'528491'),
('origin', u'Origin'),
('1q84', u'1Q84'),
('ff', u'最终幻想'),
('ec', u'EC'),
('path', u'Path'),
('chamber', u'Chamber'),
('blog', u'Blog'),
('cc', u'Creative Commons'),
('flood', u'水'),
('zh2', u'中二病'),
('1990', u'1990'),
('media', u'媒体'),
('monocle', u'Monocle'),
('iama', u'I Am A'),
('500px', u'500px'),
('pinterest', u'Pinterest'),
('global', u'海外留学'),
('gossip', u'业界八卦'),
('starwars', u'星球大战'),
('moe', u'分享萌物'),
('video', u'视频制作'),
('weibo', u'微博'),
('ideas', u'奇思妙想'),
('closed', u'关闭交易'),
('paper', u'Paper'),
('techstars', u'TechStars'),
('tangcha', u'唐茶'),
('downvoted', u'Down Voted'),
('survey', u'调查'),
('startupvisa', u'Startup Visa'),
('naq', u'不是问题的问题'),
('monthly', u'每个月都会出现的那种主题'),
('wechat', u'微信'),
('immt', u'我叫 MT'),
('soho', u'SOHO'),
('offworld', u'重口味问与答'),]),


        (4,[('music', u'音乐'),
('movie', u'电影'),
('math', u'数学'),
('photograph', u'摄影'),
('tv', u'剧集'),
('random', u'随想'),
('taste', u'美酒与美食'),
('typography', u'字体排印'),
('acg', u'ACG'),
('plant', u'植物'),
('animal', u'动物'),
('baby', u'Baby'),
('reading', u'阅读'),
('x', u'翻译'),
('writing', u'文学'),
('gomoku', u'五子棋'),
('starter', u'创造者'),
('eco', u'经济'),
('edu', u'教育'),
('boardgame', u'桌游'),
('zh', u'中文'),
('otaku', u'宅'),
('ss', u'沉默的螺旋'),
('travel', u'旅行'),
('mileage', u'行程控'),
('creditcard', u'信用卡'),
('ja', u'日本語'),
('en', u'English'),
('24', u'24 小时'),
('green', u'绿色低碳'),
('lifestyle', u'生活方式'),
('draw', u'画画'),
('exchange', u'物物交换'),
('afterdark', u'天黑以后'),
('lohas', u'乐活'),
('zakka', u'Zakka'),
('garageband', u'GarageBand'),
('beforesunrise', u'早睡早起身体好俱乐部'),
('running', u'跑步'),
('air', u'空气'),
('pet', u'宠物'),
('bike', u'骑行'),
('mushroom', u'蘑菇'),
('homme', u'Homme'),
('femme', u'Femme'),
('soccer', u'绿茵场'),
('guitar', u'吉他'),
('free', u'免费赠送'),
('coffee', u'咖啡'),
('life', u'生活'),
('nba', u'NBA'),
('olympics', u'奥运会'),
('fit', u'健康'),
('german', u'German'),]),

        (5,[('uniqlo', u'UNIQLO'),
('levis', u"Levi's"),
('gstar', u'G-Star'),
('converse', u'Converse'),
('muji', u'无印良品'),
('newbalance', u'New Balance'),
('nike', u'Nike'),
('adidas', u'Adidas'),
('diesel', u'Diesel'),
('linkinpark', u'Linkin Park'),
('bmw', u'BMW'),
('pinkfloyd', u'Pink Floyd'),
('u2', u'U2'),
('nirvana', u'Nirvana'),
('rammstein', u'Rammstein'),
('lacrimosa', u'Lacrimosa'),
('audi', u'Audi'),
('gq', u'GQ'),
('lamy', u'Lamy'),
('moleskine', u'Moleskine'),
('harukimurakami', u'村上春树'),
('thebeatles', u'The Beatles'),
('hsbc', u'汇丰银行'),
('toyota', u'丰田'),
('standardchartered', u'渣打银行'),
('citi', u'花旗银行'),
('abnamro', u'荷兰银行'),
('deutschebank', u'德意志银行'),
('ubs', u'瑞士银行'),
('wired', u'WIRED'),
('condenast', u'Condé Nast'),
('samsonite', u'Samsonite'),
('dior', u'Dior'),
('omega', u'OMEGA'),
('ef', u'EF'),
('ikea', u'宜家'),
('cartier', u'Cartier'),
('davidoff', u'Davidoff'),
('gap', u'Gap'),
('volkswagen', u'Volkswagen'),
('hm', u'H&M'),
('yippeearts', u'Yippee Arts'),
('muse', u'MUSE'),
('loreal', u"L'Oréal"),
('lancome', u'LANC?ME'),
('amazon', u'Amazon'),
('starbucks', u'Starbucks'),
('porsche', u'Porsche'),]),
        ]
        cccc='''
分享与探索
V2EX
iOS
Geek
游戏
Apple
生活
Internet
城市
品牌
        '''

        categories=[[u'分享与探索',(u'问与答',u'分享发现',u'分享创造',u'自言自语',u'分享邀请码',u'随想',u'奇思妙想',u'设计',u'Blog',u'Paper ') ],
[u'V2EX',(u'V2EX',u'Project Babel',u'Google App Engine',u'DNS',u'反馈',u'Project Picky',u'使用指南',u'OLIVIDA')  ],
[u'iOS',(u'iDev',u'iAd',u'iMarketing',u'iCode',u'iTransfer')  ],
[u'Geek',(u'程序员',u'Python',u'Android',u'Linux',u'云计算',u'Bitcoin',u'PHP',u'服务器',u'硬件',u'设计师',u'Linode',u'Kindle',u'外包',u'MySQL',u'Tornado',u'宽带症候群',u'Ruby on Rails',u'字体排印',u'Java',u'Markdown',u'编程',u'MongoDB',u'Redis',u'Ruby',u'汽车',u'商业模式',u'Photoshop',u'LEGO',u'数学',u'SONY  ')],
[u'游戏',(u'游戏',u'iGame',u'Battlefield 3',u'StarCraft 2',u'PlayStation 3',u'英雄联盟',u'Steam',u'World of Warcraft',u'EVE',u'Xbox 360',u'Wii',u'Gran Turismo  ')],
[u'Apple',(u'Mac OS X',u'iPhone',u'MacBook Pro',u'iPad',u'MacBook Air',u'配件',u'iMac',u'iPod',u'Mac mini',u'MacBook',u'MobileMe',u'iWork',u'Mac Pro',u'iLife',u'GarageBand ') ],
[u'生活',(u'二手交易',u'酷工作',u'天黑以后',u'音乐',u'电影',u'阅读',u'摄影',u'物物交换',u'美酒与美食',u'剧集',u'旅行',u'投资',u'乐活',u'Baby',u'信用卡',u'宠物',u'绿茵场',u'团购分享',u'骑行',u'咖啡',u'植物',u'非诚勿扰',u'蘑菇',u'日记',u'唐茶',u'行程控  ')],
[u'Internet',(u'Google',u'Twitter',u'Facebook',u'Path',u'Wikipedia',u'reddit',u'foursquare  ')],
[u'城市',(u'北京',u'上海',u'深圳',u'杭州',u'广州',u'成都',u'昆明',u'武汉',u'New York',u'天津',u'Los Angeles',u'San Francisco ') ],
[u'品牌',(u'UNIQLO',u'Lamy',u'宜家',u'无印良品',u'Gap',u'Moleskine',u'G-Star',u'Nike',u'Adidas  ')],]    
        
        dc ={}
        for line in categories:
            c,ns=line
            for n in ns:
                dc[n.strip()]=c  
  
        node_num = 0
        
        for i,x in enumerate(sections_names):
            num, alias, section_title = x
            section_name = alias.strip().replace(' ','').lower()
            try:
                section= Section.objects.get(name=section_name)
            except Section.DoesNotExist:
                section = Section()
                section.num = num
                section.name = section_name
                section.title = section_title
                section.title_alternative = alias
                section.save()
            
            print section
            for node  in nodes[num-1][1]:
                print node
                node_num = node_num +1
                n= Node()
                n.num = node_num
                n.section_num = section.num
                n.name = node[0]
                n.title = node[1].strip()
                n.title_alternative = node[0].capitalize()
                n.category = dc.get(n.title,'')
                n.save()

                

        # Django 1.2 compatibility
        print('OK')
